### PR TITLE
Implement tei file assembly

### PR DESCRIPTION
**Pull request by Conal-Tuohy**
This is now working with hierarchically-structured TEI documents as well as ones without any hierarchical structure. When a `div` has been split into multiple `div` elements at ingest, each in a different `surface`, this stylesheet will now stitch those fragments back together when it merges the `surface` elements into a single `text` for final TEI output.

### CODE REVIEW

**Comment by marcolarosa** [comment]
@Conal-Tuohy Can we get this pull request replaced as per yesterday's convo? I'm ready to build out this capability; just waiting on the code.

**Comment by Conal-Tuohy** [comment]
> @Conal-Tuohy Can we get this pull request replaced as per yesterday's convo? I'm ready to build out this capability; just waiting on the code.

I didn't get onto this yesterday but working on it today ... I am still working my way through the merge. It's all about the import declarations which attempt to import functions from modules which have moved to different modules from where they were 4 months ago (getStoreHandle, getLogger, etc, etc). Because the names of the imported functions were generally on a single line, that's an obstacle for the automatic merge, so I'm having to rewrite the import statements by tracking down each function. I think I'm nearly there.

**Comment by Conal-Tuohy** [comment]
Is there any chance you could merge your initial commit in this branch with the master branch, because I've been trying to reconcile them and the task just seems endless. I'm sure it would be a lot easier for you, @marcolarosa

**Comment by marcolarosa** [comment]
ok - leave it with me

**Comment by marcolarosa** [comment]
All commits cherry-picked on master and pushed

**Comment by Conal-Tuohy** [comment]
@marcolarosa I'm still seeing problems which I think indicates that the `import` issues I was struggling with weren't all about merging. Here's what I see in the log:

```
rabbit-worker1_1  | file:///srv/tasks/src/tasks/assemble-tei.js:2
rabbit-worker1_1  | import { ensureDir, copy, remove, writeFile, writeJSON, readdir } from "fs-extra";
rabbit-worker1_1  |                                                         ^^^^^^^
rabbit-worker1_1  | SyntaxError: Named export 'readdir' not found. The requested module 'fs-extra' is a CommonJS module, which may not support all module.exports as named exports.
rabbit-worker1_1  | CommonJS modules can always be imported via the default export, for example using:
rabbit-worker1_1  | 
rabbit-worker1_1  | import pkg from 'fs-extra';
rabbit-worker1_1  | const { ensureDir, copy, remove, writeFile, writeJSON, readdir } = pkg;
rabbit-worker1_1  | 
rabbit-worker1_1  |     at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
rabbit-worker1_1  |     at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
rabbit-worker1_1  | 
rabbit-worker1_1  | Node.js v18.15.0
rabbit-worker1_1  | [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Conal-Tuohy** [comment]
OK I think I've read up on this issue now and sorted it out. I believe it's the `fs-extra` package itself which changed to introduce this regression, and apparently the `import` statements we had before should never have worked.

**Pull request closed without merging**
