### PR TITLE
use schematron for before-and-after file comparisons

### PR DESCRIPTION
**Pull request by Conal-Tuohy**
I modified the schematron-validation endpoint of the `xml` service so that you can upload more than one 'instance' document to it (along with a schema). This is so that a schematron schema can be used to compare two documents, and I've used this to compare "before and after" versions of TEI files that have been through some processing, to check that nothing has been lost in the process.

(If you pass a single instance document, it's simply passed on to the schematron schema validator as is, but it you pass more than one instance document, the service assembles them into a single XML document which it then submits to the validator. Each of the uploaded documents is wrapped a in `c:file` element, and those are wrapped in a `c:directory`, where the `c:` namespace prefix refers to the namespace URI `http://www.w3.org/ns/xproc-step`. These `c:directory` and `c:file` elements are defined in the XProc specification for representing directory trees, and they're the same elements used by the `xml` service to return a set of `surface` files when a TEI file is being ingested.

I've written schematron schemas to test round-tripping of content (being ingested and paginated and then reassembled), and also to check textual integrity after ingestion, which was something that one of the unit tests used to do using SaxonJS's XPath interpreter and which I had commented out and have now deleted (the XPaths in that test have migrated into the schematron schema).

Since I was using schematron validation in both the transcription-processing and assemble-tei tests, I've moved that function into a `testing.js` library, and added the function for making scratch copies of a test data folder (which `assemble-tei` had already been doing, but without the benefit of a handy function). The dependency graph of these files is a bit messy since `assemble-tei.spec` also imports `transcription-processing` (so that it can test a full round-trip). On reflection I wonder if it'd be tidier just to lump `assemble-tei.spec.js`, `transcription-processing.spec.js`, and `testing.js` into a single file and single test suite.

Tests are all passing.

### CODE REVIEW

**Comment by Conal-Tuohy** [comment]
SaxonJS is now only used for transforming a TEI page into the HTML preview.

**Comment by marcolarosa** [comment]
Has this been rebased off master? I pushed an update to master yesterday.

**Comment by Conal-Tuohy** [comment]
> Has this been rebased off master? I pushed an update to master yesterday.

yep!

**Comment by Conal-Tuohy** [comment]
BTW using the `nyingarn/validate-with-schematron` endpoint of the XML service we do now have the functionality we need to move forward with giving users access to hints and error reports in the UI.

**Comment by marcolarosa** [comment]
ok.

Can we bundle https://github.com/CoEDL/nyingarn-workspace/issues/190 into this release?

**Comment by Conal-Tuohy** [comment]
sure ... why not. I just want to head out for a bit but I'll do that when I get back.

**Comment by Conal-Tuohy** [comment]
I've updated XProc-Z so it does now include a logger implementation. To test it, and because I thought it would be nice to have, I modified the XML service's main pipeline so that it logs each HTTP request received: the request URI, the response status code, and the response content type. 

I also changed XProc-Z so that it logs the location of the main XProc pipeline file which it's using when the service initialises, not every time a request is received.

I noticed an extra XML-parsing error message in the log when running the `transcription-processing` test suite which includes some malformed sample documents. The error message seems to be output by some library beyond my control. I'm just gonna live with it.

**Pull request merged**
